version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pokedex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokedex
    ports:
      - '5433:5432'  # Using port 5433 to avoid conflict with local PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
